import type { MonthWithParts } from "../types";

/** BASE_URL embedded in each song url */
const BASE_URL =
  "https://www.ethiopianorthodox.org/churchmusic/zema%20timehert%20bet/4%20wereb%20keamet%20eske%20amet/2%20tikemet";

export const TIKIMT: MonthWithParts = {
  id: 2,
  name: "ጥቅምት",
  parts: [
    {
      id: 1,
      name: "አመ ፭ ለጥቅምት አቡነ ገብረ መንፈስ ቅዱስ",
      songs: [
        {
          id: "169",
          title: "1 አመ ዘዋዜ ደምፀ ወተሰብከ",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/1.mp3`,
        },
        {
          id: "170",
          title: "2 ወረብ ኮከብ ብሩህ",
          filename: "2.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/2.mp3`,
        },
        {
          id: "171",
          title: "3 ወረብ ዓሥራተ ንሥአነ",
          filename: "3.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/3.mp3`,
        },
        {
          id: "172",
          title: "4 ወረብ ዝንቱሰ ገብረ ሕይወት",
          filename: "4.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/4.mp3`,
        },
        {
          id: "173",
          title: "5 ወረብ ማርያምሰ ረከብኪ ሞገሰ",
          filename: "5.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/5.mp3`,
        },
        {
          id: "174",
          title: "6 ወረ ዘአን ኮከብ ብሩህ",
          filename: "6.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/6.mp3`,
        },
        {
          id: "175",
          title: "7 አመ ዘእስ ዘይኄሊ ልብ",
          filename: "7.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/7.mp3`,
        },
        {
          id: "176",
          title: "8 ወረብ ዘእስ ንጉሥኪ ጽዮን",
          filename: "8.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/8.mp3`,
        },
        {
          id: "177",
          title: "9 ዓዲ ንጉሥኪ ጽዮን",
          filename: "9.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/9.mp3`,
        },
        {
          id: "178",
          title: "10 አመ ዘእስ ቅንዋት ወበጽጌያት ምድረ",
          filename: "10.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/10.mp3`,
        },
        {
          id: "179",
          title: "11 አመ ዘእስ ዘሰንበትአውያን ጸገዩ",
          filename: "11.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/1%20-%20tikemet%20abune%20gebre%20menfeskidus/11.mp3`,
        },
      ],
    },
    {
      id: 2,
      name: "አመ ፲ወ፪ ለጥቅምት ቅዱስ ሚካኤል",
      songs: [
        {
          id: "180",
          title: "1 አመ .ዘዚቅ  ዘላይ ቤት ዘትክል ረድኦ",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/2%20-%20tikemet%20kidus%20michael/1.mp3`,
        },
        {
          id: "181",
          title: "2 አመ ዘእስ አመንኩ አመንኩ",
          filename: "2.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/2%20-%20tikemet%20kidus%20michael/2.mp3`,
        },
        {
          id: "182",
          title: "3 አመ ዘእስ ዘሰንለዳዊት ሞገሰ",
          filename: "3.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/2%20-%20tikemet%20kidus%20michael/3.mp3`,
        },
      ],
    },
    {
      id: 3,
      name: "አመ ፲ወ፬ ለጥቅምት አቡነ አረጋዊ",
      songs: [
        {
          id: "183",
          title: "1 አመ ዘመሐ ከመ በሕዱእ ወበጽሙና",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/1.mp3`,
        },
        {
          id: "184",
          title: "2 አመ .ዘዋዜ ዔለ ውስተ አድባር",
          filename: "2.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/2.mp3`,
        },
        {
          id: "185",
          title: "3 ወረብ እስመ  ርእየ ሕማማ ለአመቱ",
          filename: "3.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/3.mp3`,
        },
        {
          id: "186",
          title: "4 ወረብ ተአጽፈ አረጋዊ",
          filename: "4.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/4.mp3`,
        },
        {
          id: "187",
          title: "5 ወረብ አዕርግርኒ ሊተ",
          filename: "5.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/5.mp3`,
        },
        {
          id: "188",
          title: "6 ወረብ አዓርግ ለልየ",
          filename: "6.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/6.mp3`,
        },
        {
          id: "189",
          title: "7 ወረብ ዘእምደብረ ደናግል",
          filename: "7.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/7.mp3`,
        },
        {
          id: "190",
          title: "8 ወረብ አይድዓኒ እስኩ",
          filename: "8.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/8.mp3`,
        },
        {
          id: "191",
          title: "9 ወረብ አረጋዊ ምሉዓ ፍቅር",
          filename: "9.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/9.mp3`,
        },
        {
          id: "192",
          title: "10 ወረብ ወከመ ወሬዛ ኀየል",
          filename: "10.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/10.mp3`,
        },
        {
          id: "193",
          title: "11 ወረብ ማርያም ከመ ዖፍ",
          filename: "11.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/11.mp3`,
        },
        {
          id: "194",
          title: "12 ወረብ አመ አመ አጕየይኪ",
          filename: "12.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/12.mp3`,
        },
        {
          id: "195",
          title: "13 ወረብ  ቦ  ዘፈለሰ ኃዲጎ ብእሲቶ",
          filename: "13.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/13.mp3`,
        },
        {
          id: "196",
          title: "14 ወረብ ትዕግሥትኪ ፈድፈደ",
          filename: "14.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/14.mp3`,
        },
        {
          id: "197",
          title: "15 ወረብ ዘአን ዘእምደብረ ደናግል",
          filename: "15.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/15.mp3`,
        },
        {
          id: "198",
          title: "16 ወረብ ዘእስ ዋካ ይእቲ",
          filename: "16.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/16.mp3`,
        },
        {
          id: "199",
          title: "17 ዓዲ  አኮ ኪያሃ የኃድጉ",
          filename: "17.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/17.mp3`,
        },
        {
          id: "200",
          title: "18 አመ ዘእስ ይሁቦሙ አስቦሙ",
          filename: "18.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/18.mp3`,
        },
        {
          id: "201",
          title: "19-አመ ዘእስ ዘሰን ንዕቀብ ትእዛዛቲሁ",
          filename: "19.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/19.mp3`,
        },
        {
          id: "202",
          title: "20-ምዕዋድ ዛ  አንቀጽ እንተ እግዚአብሔር",
          filename: "20.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/3%20-tikemet%20abune%20aregawi/20.mp3`,
        },
      ],
    },
    {
      id: 4,
      name: "አመ ፳ወ፯ ለጥቅ መድኃኔ ዓለም",
      songs: [
        {
          id: "203",
          title: "1 አመ ዘዋዜ መስቀል ኮነ",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/1.mp3`,
        },
        {
          id: "204",
          title: "2 አመ .ዘሰላም አባ ጸሊ በእንቲአነ",
          filename: "2.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/2.mp3`,
        },
        {
          id: "205",
          title: "3 አመ .ዘሰ ተንሥኢ ወንዒ",
          filename: "3.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/3.mp3`,
        },
        {
          id: "206",
          title: "4 አመ ዘሰ ናሁ ሀገረኪ",
          filename: "4.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/4.mp3`,
        },
        {
          id: "207",
          title: "5 ወረብ ኢይሰቲ ወይነ",
          filename: "5.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/5.mp3`,
        },
        {
          id: "208",
          title: "6 ወረብ ገጹ ብሩህ",
          filename: "6.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/6.mp3`,
        },
        {
          id: "209",
          title: "7 ወረብ ወልድ እኁየ",
          filename: "7.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/7.mp3`,
        },
        {
          id: "210",
          title: "8 ወረብ  .ዘአን እስመ ውእቱ ክብሮሙ",
          filename: "8.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/8.mp3`,
        },
        {
          id: "211",
          title: "9 ወረ ዘእስ ምድር ሠናይት",
          filename: "9.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/9.mp3`,
        },
        {
          id: "212",
          title: "10 ወረ ዘእስ ክነፈ ርግብ",
          filename: "10.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/10.mp3`,
        },
        {
          id: "213",
          title: "11 አመ ዘእስ ዘሰን ሰንበተ ክርስቲያን",
          filename: "11.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/6%20-%20tikemet%20medhanealem/11.mp3`,
        },
      ],
    },
    {
      id: 5,
      name: "አመ ፳ወ፱ ለጥቅ",
      songs: [
        {
          id: "214",
          title: "1 አመላ ዘወ በዓ ዘዚቅ ሃሌ ሉያ ትወጽእ በትር",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/1.mp3`,
        },
        {
          id: "215",
          title: "1 ወረብ ንዒ ኀቤየ",
          filename: "1.mp3",
          month: 2,
          day: 1,
          url: "https://www.ethiopianorthodox.org/churchmusic/zema%20timehert%20bet/4%20wereb%20keamet%20eske%20amet/3%20-%20zehidar/1%20-%20hidar%202/1.mp3",
        },
        {
          id: "216",
          title: "2 አመ ዘእስ ጸገየ ወይን",
          filename: "2.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/2.mp3`,
        },
        {
          id: "217",
          title: "3 ወረብ  ዘእስ  ዘሰን ወሠርዓ ሰንበተ",
          filename: "3.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/3.mp3`,
        },
        {
          id: "218",
          title: "4 ዓዲ ሀቡ አኰቴተ",
          filename: "4.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/4.mp3`,
        },
        {
          id: "219",
          title: "5 አመ ዘመዝ ኃደረ ላዕሌሃ",
          filename: "5.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/5.mp3`,
        },
        {
          id: "220",
          title: "6 አመ ዘአቡ ወኅሊና መንክርት",
          filename: "6.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/6.mp3`,
        },
        {
          id: "221",
          title: "7 አመ ዘአቡ ወአነሂ ዘልፈ",
          filename: "7.mp3",
          month: 2,
          day: 1,
          url: `${BASE_URL}/7%20-%20ame%2029%20le%20tikemet/7.mp3`,
        },
      ],
    },
  ],
};
